language: node_js
node_js:
  - node

before_deploy: pip install --user awscli
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync dist s3://aghataoliveira-portfolio --region=us-east-1 --delete
  skip_cleanup: true
